### PR TITLE
GSNGM-689: Added KML layers: re-arrange the Data displayed panel content

### PR DESCRIPTION
**Pull request by b4l**

### CODE REVIEW

**Comment by vladyslav-tk** [comment]
@b4l need to remove a layer from the list after page reload because empty line shown

**Comment by b4l** [comment]
@vladyslav-tk how to do this? add a new layer type and remove them from ngm-layers in the first update function?

**Review by vladyslav-tk — APPROVED** [review]
@b4l I added a fix, please have a look and merge if it looks OK for you

**Comment by b4l** [comment]
> @b4l I added a fix, please have a look and merge if it looks OK for you

Thanks, looks fine! Waiting for ci to merge.

**Pull request merged**
